In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import cufflinks as cf

In [2]:
df = pd.read_csv('https://gist.githubusercontent.com/bigsnarfdude/515849391ad37fe593997fe0db98afaa/raw/f663366d17b7d05de61a145bbce7b2b961b3b07f/weather.csv')

In [3]:
df

     outlook temperature humidity  windy play
0   overcast         hot     high  False  yes
1   overcast        cool   normal   True  yes
2   overcast        mild     high   True  yes
3   overcast         hot   normal  False  yes
4      rainy        mild     high  False  yes
5      rainy        cool   normal  False  yes
6      rainy        cool   normal   True   no
7      rainy        mild   normal  False  yes
8      rainy        mild     high   True   no
9      sunny         hot     high  False   no
10     sunny         hot     high   True   no
11     sunny        mild     high  False   no
12     sunny        cool   normal  False  yes
13     sunny        mild   normal   True  yes

In [8]:
df.plot(kind='bar')

TypeError: no numeric data to plot

In [9]:
df.drop(columns='windy')

     outlook temperature humidity play
0   overcast         hot     high  yes
1   overcast        cool   normal  yes
2   overcast        mild     high  yes
3   overcast         hot   normal  yes
4      rainy        mild     high  yes
5      rainy        cool   normal  yes
6      rainy        cool   normal   no
7      rainy        mild   normal  yes
8      rainy        mild     high   no
9      sunny         hot     high   no
10     sunny         hot     high   no
11     sunny        mild     high   no
12     sunny        cool   normal  yes
13     sunny        mild   normal  yes

In [10]:
df.plot()

TypeError: no numeric data to plot

In [1]:
df.plot('tips')

NameError: name 'df' is not defined